spring.application.name=app
# URL of db H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# console of H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# hibernate of JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
